file(STRINGS ${CMAKE_CURRENT_LIST_DIR}/version.txt PROINFO_STR)
string(REPLACE ":" ";" PROINFO_LST ${PROINFO_STR})
list(GET PROINFO_LST 0 LIB_NAME)
list(GET PROINFO_LST 1 LIB_VER)
message(STATUS ${LIB_NAME} ", LIB_VER:" ${LIB_VER})

string(REPLACE "." "," VERSION_FILE ${LIB_VER})
message(STATUS ${LIB_NAME} ", VERSION_FILE: " ${VERSION_FILE})

add_definitions(-DLINKSENSEVERSION=":${LIB_VERSION_NUMBER}")
configure_file(
    ${CMAKE_CURRENT_LIST_DIR}/Resource.rc.in
    ${CMAKE_CURRENT_LIST_DIR}/Resource.rc
    @ONLY)

# out info varibles
set(LIB_FILEVERSION ${VERSION_FILE})
set(LIB_VERSION_NUMBER ${LIB_VER})
set(LIB_FILENAME ${LIB_NAME})
set(LIB_VERSION_FILES ${CMAKE_CURRENT_LIST_DIR}/Resource.rc ${CMAKE_CURRENT_LIST_DIR}/resource.h)
message(STATUS ${PROJECT_NAME} "LIB_VERSION_FILES: " ${LIB_VERSION_FILES})
